export { default as HomeSection } from './Home'
export { default as AboutSection } from './About'
export { default as ServiceSection } from './Services'
export { default as MenuSection } from './Menu'
export { default as FoodSection } from './FoodGllary'